### PR TITLE
Server environment

### PR DESCRIPTION
**Pull request by TDu**

### CODE REVIEW

**Review by elicoidal — COMMENTED** [review]
@TDu Thanks for your contribution.
Can you split the PR in 2: one for auditlog and the other for server_environment for readability/traceability?

Is this a migration PR? This is not clear neither with the PR name or the description.

**Comment by yvaucher** [comment]
@TDu You probably don't want audit log module in this PR

**Comment by yvaucher** [comment]
@TDu could you also squash the OCA bot translation commits into one ?

**Review by yvaucher — CHANGES_REQUESTED** [review]
OCA bot commit to squash
+ removing commits of auditlog

**Comment by TDu** [comment]
Tanks for the comments.
I removed the commit regarding audit log.
Squashed the translation bot commits.

**Comment by yvaucher** [comment]
Thanks :+1:

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
@TDu just one last thing,

Can you squash commits:

c1e4dad Remove Travis test split for database_cleanup
4fdac36 [FIX] bug on view by changing generated table field name

The first commit seems only a useless `#` character which is removed in second commit

**Review by guewen — APPROVED** [review]

**Pull request merged**
