### PR TITLE
[18.0][MIG] server_environment from 17.0

### PR DESCRIPTION
**Pull request by sbidoul**
First 18.0 PR to test the project template.

- I also add the ruff config improvements: https://github.com/OCA/oca-addons-repo-template/pull/273
- ~the xml prettifier improvements: https://github.com/OCA/oca-addons-repo-template/issues/224~

### CODE REVIEW

**Comment by sbidoul** [comment]
@moylop260 can you help with the `po-pretty-format` issue here? I don't understand what the error means.

**Comment by sbidoul** [comment]
The other issue is that the current `.eslintrc.yml` is not compatible with the latest `eslint`, and eslint-precommit does not seem to work well with pre-commit...

**Comment by rousseldenis** [comment]
> @moylop260 can you help with the `po-pretty-format` issue here? I don't understand what the error means.

Currently on it.

Try regenerating .pot file.

**Comment by SirAionTech** [comment]
> The other issue is that the current `.eslintrc.yml` is not compatible with the latest `eslint`, and eslint-precommit does not seem to work well with pre-commit...

Try including https://github.com/SirAionTech/server-env/commit/d8e1926a14faa9b2a2c88a9f41f7cd5e3e73d489; I'll try to include it in the addons repo template in the next few days or more probably after the experience

**Comment by sbidoul** [comment]
@SirAionTech I worry that this adds additional dependencies that are not pinned.

I don't know, if we don't find a good solution soon, we'll start with the same eslint version as in 17. And we then have a year to modernize..

**Comment by sbidoul** [comment]
:green_apple:

**Comment by sbidoul** [comment]
Don't merge just yet, I need to restart the bot.

**Comment by sbidoul** [comment]
Ok, bot is ready.

**Comment by moylop260** [comment]
> @sbidoul 
>
> @moylop260 can you help with the po-pretty-format issue here? I don't understand what the error means.

Checking...

**Comment by moylop260** [comment]
@sbidoul 

It needs the following args in order to autofix it:

```diff
 - repo: https://github.com/OCA/odoo-pre-commit-hooks
     rev: v0.0.33
     hooks:
       - id: oca-checks-odoo-module
       - id: oca-checks-po
+        args:
+          - --fix
```

OFFTOPIC: BTW I will show the diff if the parameter is not defined for wrong-format

UPDATED: https://github.com/OCA/odoo-pre-commit-hooks/issues/110

UPDATED2: Agree disabling it https://github.com/OCA/oca-addons-repo-template/pull/274

**Comment by pedrobaeza** [comment]
The pre-commit auto-fixes commit is after the migration commit, but not being critical, let's try to merge the module to see if any problem:

/ocabot merge nobump

**Pull request merged**
