### PR TITLE
[UPD] Change LICENSE to LGPL

### PR DESCRIPTION
**Pull request by ivantodorovich**
ping @simahawk @guewen 

Following up on your comment here: https://github.com/OCA/server-env/pull/76#discussion_r664276443

> after checking it seems there's a bit of confusion on licenses.
>
>The main module says GPL but refers to AGPL link, the tech mixing says AGPL but seems wrong to me.
>
>Would you mind opening another PR to fix them so that we can fast track it?

Would you mind point out what you saw?
If it's indeed LGPL what we need here, do we also need to change the license of the modules that depend on it?

Also what about this file?
If it's based on someone else's work I don't think we can change it, right?
https://github.com/OCA/server-env/blob/314d16d37c8ce56603c3d1ad9c2ff596d1f22425/server_environment/server_env.py#L1-L19

### CODE REVIEW

**Review by simahawk — CHANGES_REQUESTED** [review]
regarding `GPL` change we have to ask @nbessi and @guewen.

My remark  was that the header was referring to `GPL` but linking the `AGPL` license.

Very likely there was a reason for going w/ GPL. For the tech mixin I don't care that much but it should probably be the same as the rest of the module.

CC @gurneyalex

**Comment by guewen** [comment]
I have no idea why originally it was GPL, but AFAIR this module dates from OpenERP 5.0, which was GPL.
Considering 

>    Adapted by Nicolas Bessi. Copyright Camptocamp SA 
>    Based on Florent Xicluna original code. Copyright Wingo SA 

I suppose @nbessi and @florentx (hi!) may know better than me if we can change the license :)
Apparently, the code that goes back from the original module is mainly the one that generates the view dynamically https://github.com/OCA/server-env/blob/314d16d37c8ce56603c3d1ad9c2ff596d1f22425/server_environment/server_env.py#L176-L315 and system info https://github.com/OCA/server-env/blob/314d16d37c8ce56603c3d1ad9c2ff596d1f22425/server_environment/system_info.py

**Comment by nbessi** [comment]
Purely for historical reason. Fine for me we can move to LGPL.

**Review by sbidoul — APPROVED** [review]

**Review by simahawk — APPROVED** [review]

**Pull request merged**
