### PR TITLE
[MIG] [13.0] mail_environment

### PR DESCRIPTION
**Pull request by gurneyalex**
depends:
* [x] #29

### CODE REVIEW

**Review by grindtildeath — APPROVED** [review]
LGTM :+1:

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
@gurneyalex #29 merged, you can rebase

**Review by yvaucher — APPROVED** [review]
LGTM

**Comment by yvaucher** [comment]
This fails due to ~https://github.com/OCA/server-env/pull/33~ https://github.com/OCA/server-env/pull/36

**Comment by sbidoul** [comment]
@gurneyalex @yvaucher can you do the `pre-commit run -a` dance so this can be merged?

**Comment by HviorForgeFlow** [comment]
I think a manual rebase is required.

**Comment by guewen** [comment]
Rebased and run `pre-commit run -a`

**Pull request merged**
