### PR TITLE
[14.0] server_environmnet: allow to overwrite odoo config options

### PR DESCRIPTION
**Pull request by petrus-v**
from server_environment_files module

### CODE REVIEW

**Review by damdam-s — APPROVED** [review]
LGTM

**Review by Koudja — APPROVED** [review]

**Comment by petrus-v** [comment]
I've rebase and the pre-commit step failed at the same point, I've create a new PR to bump copier template version and move to ruff here https://github.com/OCA/server-env/pull/176, maybe this PR can wait a bit more the other to get merged

**Comment by petrus-v** [comment]
@thomaspaulb I've just rebased the PR, CI looks ok now !

**Pull request merged**
