### PR TITLE
[11.0][FIX] server_environment: running_env default to `test`

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Backport of https://github.com/OCA/server-env/pull/45

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza @simahawk seems right?

**Comment by alexey-pelykh** [comment]
Runbot should fail due to this:
```
2020-04-15 17:52:04,141 173 WARNING openerp_test odoo.addons.server_environment.serv_config: `running_env` not found. Using default = `test`.
2020-04-15 17:52:04,141 173 WARNING openerp_test odoo.addons.server_environment.serv_config: We strongly recommend against using the rc file but instead use an explicit config file or env variable.
```

**Review by simahawk — APPROVED** [review]
thanks Alexey

**Comment by pedrobaeza** [comment]
Let's go for it for having it fixed

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
haha, duplicated, I'm removing mine.

**Comment by simahawk** [comment]
hahah same time :D

**Review by bodedra — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Do we need same for v12?

**Pull request merged**
