### PR TITLE
[MIG] 15.0 server_environment_ir_config_parameter

### PR DESCRIPTION
**Pull request by JuMiSanAr**
Depends on 

- [ ] ~~https://github.com/OCA/server-env/pull/83~~
- [x] https://github.com/OCA/server-env/pull/87 (replaces #85)

### CODE REVIEW

**Review by leemannd — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by sbidoul** [comment]
The last commit has ci skip. So tests did not run.

**Comment by simahawk** [comment]
```
Run oca_install_addons
+ setuptools-odoo-get-requirements --include-addons --addons-dir .
+ cat test-requirements.txt
+ pip install -r test-requirements.txt
odoo-addon-server_environment>=15.0dev,<15.1dev
odoo>=15.0a,<15.1dev
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://wheelhouse.odoo-community.org/oca-simple-and-pypi
ERROR: Could not find a version that satisfies the requirement odoo-addon-server_environment<15.1dev,>=15.0dev (from versions: none)
ERROR: No matching distribution found for odoo-addon-server_environment<15.1dev,>=15.0dev
Error: Process completed with exit code 1.
```
missing https://github.com/OCA/server-env/pull/83

**Comment by simahawk** [comment]
@JuMiSanAr base PR merged finally

**Pull request merged**
