### PR TITLE
[MIG] mail_environment: Migration to 16.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
Dependency changes because of :
https://github.com/OCA/OpenUpgrade/blob/16.0/openupgrade_scripts/apriori.py#L34

No other changes

No risk of  breaking change in behavior comparing to previous versions

Nice, thanks to @adrienpeiffer

**Review by florian-dacosta — APPROVED** [review]
LGTM

**Comment by simahawk** [comment]
LG, thanks

/ocabot migration mail_environment
/ocabot merge nobump

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Comment by etobella** [comment]
@adrienpeiffer There is some problems with the pre-commit (probably due to flake8-calypse :laughing: )

Can you update it in another PR please :pray:

**Comment by etobella** [comment]
I fixed pre-commit on #133 
Let's try again:
/ocabot merge nobump

**Comment by simahawk** [comment]
@adrienpeiffer any special reason why `smtp_authentication` was not included in the env fields?

**Pull request merged**
