### PR TITLE
ADD module carrier_environment

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Review by angelmoya — APPROVED** [review]
:+1:

**Comment by angelmoya** [comment]
@jctrey check this pr to use as dependency in tracking link modules

**Comment by angelmoya** [comment]
Maybe we need also selection field, like we use carrier_type.

Then we can set carrier_account on carrier_delivery, this way we can now carrier_type on pickings.

**Review by florian-dacosta — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
