### PR TITLE
[14.0][MIG] - migration mail_environment

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by hparfr — APPROVED** [review]

**Review by p-tombez — APPROVED** [review]
Looks good, functional tests -> OK

**Review by guewen — APPROVED** [review]
I think you need to rebase

**Comment by StephaneMangin** [comment]
@sbejaoui Hi Bejaoui, do you have time to finish this PR (I will need it, so probably fork it and finish it today)

**Comment by sbejaoui** [comment]
> @sbejaoui Hi Bejaoui, do you have time to finish this PR (I will need it, so probably fork it and finish it today)

travis is green now

**Pull request merged**
