### PR TITLE
server_environment: Update label of env default field to avoid warnin…

### PR DESCRIPTION
**Pull request by adrienpeiffer**
…g messages

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
The warning we want to silence is `odoo.addons.base.models.ir_model: Two fields (smtp_host_env_default, smtp_host) of ir.mail_server() have the same label: SMTP Server`

**Comment by sbidoul** [comment]
@simahawk @gurneyalex

**Review by lmignon — APPROVED** [review]

**Review by simahawk — APPROVED** [review]
LG. @adrienpeiffer pls next time keep the commit msg short and move the long description to the description of the commit.

See also https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#commit-message-structure

**Comment by simahawk** [comment]
I guess this should be backported to older versions?
If yes, pls rewrite the commit msg 1st otherwise when we fwd/backport commits we'll always have a false positive.

**Comment by adrienpeiffer** [comment]
@simahawk Commit updated. Thanks

**Pull request merged**
