### PR TITLE
[17.0][MIG] data_encryption: Migration to 17.0

### PR DESCRIPTION
**Pull request by map-240221**

### CODE REVIEW

**Comment by mkrnac** [comment]
when this PR can be merged?

**Comment by pedrobaeza** [comment]
It requires reviews: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

**Review by florian-dacosta — APPROVED** [review]
LGTM code review.
I think you could squash the 2 last commits together though

**Comment by map-240221** [comment]
Squashed the commits into one

**Comment by florian-dacosta** [comment]
Thanks 

@moitabenfdz @bguillot Could you review please?

**Comment by hparfr** [comment]
please remove the pandoc file

**Review by hparfr — CHANGES_REQUESTED** [review]
pandoc-3.3-1-amd64.deb is in "[IMP] data_encryption: pre-commit auto fixes" commit

**Comment by map-240221** [comment]
> pandoc-3.3-1-amd64.deb is in "[IMP] data_encryption: pre-commit auto fixes" commit

Removed and changes squashed into the last commit

**Comment by pedrobaeza** [comment]
That's not correct, as it was introduced in the commit "[IMP] data_encryption: pre-commit auto fixes", so you have the double diff, adding and removing it. You must do it in the previous commit.

**Comment by map-240221** [comment]
Thanks for the correction. Rebased the last two commits and made the changes in the designated commit, hopefully no more technical (non-functionality) issues.

**Comment by pedrobaeza** [comment]
Yes, that part is correct.

**Review by hparfr — APPROVED** [review]

**Comment by hparfr** [comment]
Thanks @map-240221

**Pull request merged**
