### PR TITLE
[MIG] server_environment_ir_config_parameter: Migration to 13.0

### PR DESCRIPTION
**Pull request by grindtildeath**
depends on:

- [x] #29

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by Tonow-c2c — APPROVED** [review]
@grindtildeath You have dependence error in travis
but code LGTM

**Review by yvaucher — APPROVED** [review]
LGTM

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by simahawk** [comment]
@grindtildeath can you rebase?

**Comment by yvaucher** [comment]
@grindtildeath seems that you also need to re-run the pre-commit hook.
Black will have to replace some `'` by `"`

**Comment by grindtildeath** [comment]
@yvaucher Should be better now :)

**Comment by yvaucher** [comment]
@grindtildeath good one step further lint passes now.

But pytest fails on some tests of this module.

**Review by yvaucher — APPROVED** [review]
:tada: thanks for the fix in the tests

Good to be merged.

**Pull request merged**
