### PR TITLE
[FIX] removed static folders, added preloadable key in manifest

### PR DESCRIPTION
**Pull request by ntsirintanis**
Removed `static` folder and added `preloadabe` key in manifests for `mail_environment`, `server_environment_*`.

See here why:
[OCA/server-auth#84](https://github.com/OCA/server-auth/pull/84)
[OCA/maintainer-tools#418](https://github.com/OCA/maintainer-tools/pull/418)

@hbrunn

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@ntsirintanis please, backport or forward port to all versions affected.

**Comment by hbrunn** [comment]
@ntsirintanis please squash your commits for merging

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
Does this need forward porting?

**Pull request merged**
